### ISSUE TITLE
Séance de travail

### ISSUE THREAD

**Issue by jflyXX** [FilmINT/organization#5]
Bonjour @rgrunbla,

Nous avions une séance de travail de prévu avec vous aujourd'hui à 14h. Cependant je n'ai pas réussi à vous contacter par téléphone.

Serait-il possible de programmer une nouvelle séance de travail ?

Cordialement @jflyXX

**Comment by jflyXX** [comment]
Bonjour @rgrunbla 

Veuillez m'excuser pour le retard j'ai complétement oublié de reprogrammer la séance de travail. De plus @Nishogi m'a fait remarquer que vous aviez envoyé un message pour demander les horaires mais je n'ai pas reçu de mail de notifications et le message a disparu on dirait. Donc pour la réunion je pensais vous proposer mercredi 29 avril de 15h à 17h. Si jamais cela ne convient pas on peut essayer de trouver un autre horaire.

Cordialement @jflyXX

**Comment by rgrunbla** [comment]
Je ne suis pas dispo le 29 mars (si c'est bien du 29 mars dont on parle) @jflyXX @Nishogi @kimgeorget @FlorianParfant 

Je pense qu'il faudrait faire une petite réunion de pas longtemps du tout (1h max) dès qu'on peut. !etes vous disponibles ce vendredi ?

**Comment by jflyXX** [comment]
On est dans une période chargé actuellement avec des CF2 et CF1 donc on n'a peu d'horaire disponible ensemble. On a trouvé en commun le vendredi 31 mars de 16h15 à 17h15 par exemple si cela vous convient @rgrunbla ?

**Comment by rgrunbla** [comment]
Très bien ! On peut faire ça en visio ou en présentiel : que préférez vous ?

**Comment by rgrunbla** [comment]
Hello @jflyXX @Nishogi @kimgeorget @FlorianParfant,

On fera la réunion de cet après-midi en visio. Envoyez moi un lien sur la plateforme de votre choix, quelques minutes avant le début du créneau,

Rémy

**Comment by rgrunbla** [comment]
Je suis dans la salle d'attente @jflyXX.
